### ISSUE TITLE
add_p() t.test method change rendering issue

### ISSUE THREAD

**Issue by postgres-newbie** [ddsjoberg/gtsummary#1209] opened 2022-04-20 20:05 UTC
When generating a tbl_summary, if an add_p(test = everything() ~ "t.test") was used and later the tbl_summary object (let's call it: sample_tbl_summary) was run through the statement:  
add_p(sample_tbl_summary, test = everything() ~ aov), 
the output in viewer still displays the p-values from the t.test instead of updating them to those obtained from an ANOVA.

**Comment by ddsjoberg** [comment] 2022-04-20 20:12
Thank you for your post. Please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates the issue you're reporting. Take just a few minutes to review [reprex.tidyverse.org ](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

I am going to go ahead and close this issue for now. But please do re-open the issue after you've added your reproducible example.

**Comment by postgres-newbie** [comment] 2022-04-20 21:30
Here's some reproducible code:

library(gtsummary); 
library(gt); 
library(survival) 
library(dplyr); 
library(stringr); 
library(purrr); 
library(forcats); 
library(tidyr)

save_tbl_summary<-trial %>%
  select(response, age, grade) %>%
  mutate(response = factor(response, labels = c("No Tumor Response", "Tumor Responded"))) %>%
  tbl_summary(
    by = response,
    missing = "no",
    label = list(age ~ "Patient Age", grade ~ "Tumor Grade")
  ) %>%
  add_p(pvalue_fun = ~style_pvalue(.x, digits = 2)) %>%
  add_q()

# The p-value that gets rendered is >0.9 when it is 0.813
add_p(save_tbl_summary, test = everything() ~ "aov")

# Here is the p-value when calculated using "aov"
aov(as.numeric(as.factor(grade)) ~ as.factor(response), 
    data = subset(trial, subset= response %in% c(1, 0))) %>% summary()

#                      Df Sum Sq Mean Sq F value Pr(>F)
# as.factor(response)   1   0.04  0.0383   0.056  0.813 # The p-value that gets rendered is >0.9 when it is 0.813
# Residuals           191 129.88  0.6800              

# Here's the code to show that the chisel.test p-value gets reported which is 0.93
chisq.test(x = trial$response[which(trial$response %in% c(0, 1))], 
           y = trial$grade[which(trial$response%in% c(0, 1))])

# Pearson's Chi-squared test
# 
# data:  trial$response[which(trial$response %in% c(0, 1))] and trial$grade[which(trial$response %in% c(0, 1))]
# X-squared = 0.15014, df = 2, p-value = 0.9277

**Comment by ddsjoberg** [comment] 2022-04-20 21:38
Thanks for adding the example.

I wasn't expecting users to run `add_p()` multiple times on the same table. It looks like I need add a check that the p-value column is not already present, and if it is then throw an error.

**Comment by postgres-newbie** [comment] 2022-04-20 23:01
Yes, an error message would be nice or what would be better is to allow for the p-values to be overwritten in the rendered version with the new method.

**Comment by ddsjoberg** [comment] 2022-04-20 23:04
you can create another table and merge them together with `tbl_merge()`. We rely on the column names, so cannot allow more than one run without causing issues downstream

**Comment by ddsjoberg** [comment] 2022-04-20 23:56
error messaging added to main branch

**Closed by ddsjoberg** 2022-04-20 23:56 UTC
