### ISSUE TITLE
Feature request: Align on decimal place in regressions with SE below coefficient

### ISSUE THREAD

**Issue by kendonB** [ddsjoberg/gtsummary#1310] opened 2022-08-15 02:11 UTC
**Is your feature request related to a problem? Please describe.**
In many fields, regressions are presented like those in #675, withe SEs below estimates and the numbers aligned on the decimal place, _by estimate_. The problem is that tbl_regression with add_significance_stars does not align estimates with SEs by the decimal place. 

**Describe the solution you'd like**
Functionality to align coefficient-SE pairs by decimal place. In Word and LaTeX, the best solution I know is to create one table environment for each pair, nested inside the larger table environment, then use the standard approach to align on decimal.

**Describe alternatives you've considered**
`stargazer` can do some of this, but doesn't provide the nice grammar for otherwise editing tables.

**Comment by ddsjoberg** [comment] 2022-08-15 02:22
Hi @kendonB , Thanks for the note and the request.

Can you link to some reporting guidelines from journals that require decimal point alignment? I can review and see what we can support.

**Comment by kendonB** [comment] 2022-08-15 02:46
I haven't been able to find a journal style guide that requires this, though it appears in many journal articles. Might be a nice-to-have for journals but not a requirement.

**Comment by ddsjoberg** [comment] 2022-08-15 12:41
Unfortunately, the package was not written with aligned decimal points in mind, and I am not sure how to support it natively (you can likely hack something together, however).

Essentially, what is happening internally is there is a data frame wit the estimate and the SE in a row. We first apply a formatting function to round the estimates and convert them to character. Then we use `glue()` to combine them into a single cell, then we print the data frame.

I think you could hack something together with these steps:
1. Select a fixed-width font for the table.
2. Modify the functions that format the estimate and SE in such a way that padding of blank spaces on each side result in an alignment of the decimal places.
3. This sounds tedious, sorry!

**Comment by kendonB** [comment] 2022-08-15 22:56
I know that gtsummary is focused on html output, but I would guess most people using the package in this way would want output in LaTeX or Word.

For both LaTeX and Word, we are actually almost there.

Your answer [here](https://stackoverflow.com/questions/73356731/how-to-translate-se-below-coefficient-table-to-latex-in-gtsummary/73361077#73361077) gives:

``` r
library(gtsummary)
#> #StandWithUkraine

tbl <-
  lm(time ~ ph.ecog + sex, survival::lung) %>%
  tbl_regression(label = list(ph.ecog = "ECOG Score", sex = "Sex"))

add_significance_stars_ex3 <-
  tbl %>%
  add_significance_stars(
    hide_se = TRUE,
    pattern = "{estimate}{stars}  \n({std.error})"
  ) %>%
  modify_header(estimate ~ "**Beta (SE)**") %>%
  modify_footnote(estimate ~ "SE = Standard Error", abbreviation = TRUE) 

add_significance_stars_ex3 %>%
  as_kable_extra(escape = FALSE, format = 'latex') %>%
  cat()
#> 
#> \begin{tabular}{l|c}
#> \hline
#> \textbf{Characteristic} & \textbf{Beta (SE)}\\
#> \hline
#> ECOG Score & \makecell[c]{-58**\ \ \\(19.1)}\\
#> \hline
#> Sex & \makecell[c]{52\ \ \\(27.9)}\\
#> \hline
#> \multicolumn{2}{l}{\rule{0pt}{1em}\textsuperscript{1} \textit{p<0.05; \textbf{p<0.01; }}p<0.001}\\
#> \multicolumn{2}{l}{\rule{0pt}{1em}\textsuperscript{2} SE = Standard Error}\\
#> \end{tabular}
```
The result is:
![image](https://user-images.githubusercontent.com/5327505/184727612-ee868120-5ed0-44c6-b7a2-a2d0bdc85d76.png)

We just need to switch `makecell` to a `tabular` environment, then add:
```
\usepackage{siunitx}
\sisetup{input-symbols = ()}
```
at the top, and switch to an `S` column (just the first one here):
```
\begin{tabular}{l|c}
\hline
\textbf{Characteristic} & \textbf{Beta (SE)}\\
\hline
ECOG Score & \begin{tabular}{S[table-format=3.2]}-58.99**\\(19.1)\end{tabular}\\
\hline
Sex & \makecell[c]{52\ \ \\(27.9)}\\
\hline
\multicolumn{2}{l}{\rule{0pt}{1em}\textsuperscript{1} \textit{p<0.05; \textbf{p<0.01; }}p<0.001}\\
\multicolumn{2}{l}{\rule{0pt}{1em}\textsuperscript{2} SE = Standard Error}\\
\end{tabular}
```
![image](https://user-images.githubusercontent.com/5327505/184728549-dc7b2c2d-12fa-4e80-b6e7-c2e674627b6b.png)

The stars placement is determined by the `2` in `table-format=3.2` as that seems to be the number of spots to the right of the decimal place. `3` is the number of spots to the left of the decimal place.

So the issue for LaTeX (working with gtsummary) is with the kableExtra LaTeX converter, yes?

The for Word output I managed to convert to `flextable`, immediately save, followed the instructions [here](https://www.myofficetricks.com/how-to-align-decimal-point-in-word-table-cells/), and got this:

![image](https://user-images.githubusercontent.com/5327505/184734293-973c7ec7-da73-4dd3-9a37-a54a1f875b4a.png)

Again, flextable would have to be the ones to do this.

**Comment by ddsjoberg** [comment] 2022-08-15 23:36
Wow, you're a talented typesetter!

1. I had no idea Word could align anything by decimal point 🤯 
2. In the background, gtsummary is using `knitr::kable()` with `kableExtra::linebreak()` to construct the line breaks. It's this second function that uses `makecell{}`, I believe. Honestly, I don't use PDF output much (I used Word and HTML primarily), and it's been a while since I wrote this code and would need time to familiarize myself again to be certain.

**Comment by kendonB** [comment] 2022-08-16 00:03
I am also using Word more now - so I'm interested in both. Do you recall how it works for the `flextable` to Word workflow?

**Comment by ddsjoberg** [comment] 2022-08-16 01:13
You can see 100% of the formatting I perform on an object with

```r
lm(mpg ~ cyl, mtcars) |> tbl_regression() |> as_flex_table(return_calls = TRUE)
```

**Comment by ddsjoberg** [comment] 2022-08-16 19:58
@kendonB I am going to go ahead and close this issue. I don't think this is something I could add internally for the all the print engines. I think you should be able to hard-code this into the cells you want to align

**Closed by ddsjoberg** 2022-08-16 19:58 UTC

**Comment by capnrefsmmat** [comment] 2022-10-24 23:21
It looks like gt is adding support for aligning at decimals: https://gt.rstudio.com/reference/cols_align_decimal.html

This isn't in a released version yet, but was [added a month ago](https://github.com/rstudio/gt/commit/3cddb81321a4ecd8643e3350428aa849761b82d4).

Aligning at decimal points is a common recommendation for numeric columns because it makes it easy to compare the order of magnitude of different values quickly. The alternative is to right-align numbers and round them to the same number of decimal places. If the gt support is sufficient, it'd be a useful feature to have by default.

**Comment by ddsjoberg** [comment] 2022-10-24 23:31
This could work on the coef column of a regression summary. Let me know!
