### ISSUE TITLE
Adding strata to tables

### ISSUE THREAD

**Issue by asshah4** [ddsjoberg/gtsummary#679] opened 2020-10-09 11:07 UTC
**Is your feature request related to a problem? Please describe.**
I think this is a nearly universal problem in packages oriented around making summary tables. Its difficult to summarize by group, and if its possible, it can only be done for a single layer. In epidemiological studies, I tend to summarize not only by some variable, but also split the data between an additional group. I'm not sure what the correct terminology is, perhaps **strata**?

**Describe the solution you'd like**
I would love to see a feature like an `add_strata()` function, such that a `tbl_summary()` that includes a grouping variable can be split amongst an additional variable. 

What I currently do, as I've continually struggled with a uniform approach to tables until the `gt` package (and subsequently the `gtsummary` package), is to create different data sets and then apply a `tbl_merge()`, which is adequate but somewhat redundant.

```
library(tidyverse)
library(gt)
library(gtsummary)

coupe <- 
	gtcars %>%
	filter(bdy_style == "coupe") %>%
	select(drivetrain, msrp) %>%
	tbl_summary(by = drivetrain)

sedan <- 
	gtcars %>%
	filter(bdy_style == "sedan") %>%
	select(drivetrain, msrp) %>%
	tbl_summary(by = drivetrain)

tbl_merge(list(coupe, sedan), tab_spanner = c("Coupe", "Sedan"))
```

This requires filtering the data pre-summary. I think some issues that may arise is how to handle statistics, how many strata, etc. 

If this feature is actually available, I wasn't able to find it and I apologize.

**Comment by ddsjoberg** [comment] 2020-10-09 23:04
Hi @asshah4 ! Thanks for the suggestion.  You're correct that this is currently not possible, and the solution you outlined is the general approach I would recommend.

I'll leave this Issue open and think on whether/how to implement something like this.

In the meantime, here's a way to update your code, so you don't need to repeat any `tbl_summary()` code (repeating code can be annoying!).

```r
library(gtsummary)
library(tidyverse)

# make compact tables
theme_gtsummary_compact()

# nest variables by stratification variable `bdy_style`
tbls <-
  gt::gtcars  %>%
  select(bdy_style, drivetrain, msrp) %>%
  mutate(drivetrain = factor(drivetrain)) %>%
  group_nest(bdy_style) %>%
  # build tbls seperately by `bdy_style`
  rowwise() %>%
  mutate(
    tbl = tbl_summary(data, by = drivetrain, type = everything() ~ "continuous") %>% list()
  ) 

# merging tables
tbl_merge(tbls$tbl, tab_spanner = str_glue("**{tbls$bdy_style}**"))
```

![image](https://user-images.githubusercontent.com/26774684/95638135-9e5e0780-0a61-11eb-9637-878030b745c2.png)


Things to consider about implementing something like this:
1. Each nested dataset may result in different table defaults...this will be difficult to ensure the same options are being used in every table before they are merged.
1. If the `by=` variable is not a factor, then various subsets may not have the same levels observed.
1. Implementing this is essentially a fancy `apply()` where consistent args are passed to each subset dataset, with either a `tbl_merge()` or `tbl_stack()` at the end to combine tables.

**Comment by aghaynes** [comment] 2020-10-14 07:08
@asshah4, FYI the `atable` package has a solution for this... atable has quite a different approach but is also very flexible...

```
install.packages("atable")
library(atable)
data(mtcars)
atable(mtcars,
       target_cols = c("mpg", "vs"),
       group_col = "am",
       split_cols = "cyl")
# or
atable(mpg + vs ~ am | cyl, mtcars)
```

**Comment by aspina7** [comment] 2020-12-18 11:09
Hello, big fan of your package! 
Would like to second this request please. 
As part of the [r4epis project](https://github.com/R4EPI) we created some [tab functions](https://github.com/R4EPI/epibuffet) for simple summary stats, univariate estimates (e.g. odds ratios, risk ratios and incidence rate ratios, incl option for stratified estimates) and survey weighted tables. 
As discussed here, we were hoping to retire all these functions and use your great package but the only thing that is missing is this option for stratified estimates - e.g. mantel haenszel odds ratios. 
Would be really awesome if you could use some of what we have already set up - [including tests ](https://github.com/R4EPI/epibuffet/blob/master/tests/testthat/test-tab_univariate.R) - then we would just switch to using {gtsummary} for everything! 
Thanks a lot!

**Comment by ddsjoberg** [comment] 2020-12-18 11:50
Thanks for the note. We're looking into this more and how it can fit within the gtsummary framework.

Can you copy and example table if why you have in mind for your stratified table that includes the MH ORs? It's very helpful to have a precise idea what you have in mind.

**Comment by aspina7** [comment] 2020-12-18 14:10
For our epibuffet::tab_univariate function we stacked the output a little, see bottom of page [here](https://r4epis.netlify.app/training/walk-through/univariate/)
But traditionally it would probably be presented as below (though guess stratified tables wouldnt often be shown in publications or reports). 
re your suggestions above for implementation - I think I would favour your first suggestion above of specifying a group_* argument prior to running tbl_* (to be in keeping with other dplyr typ manipulations), however the add_strata at end might be easier to do and not sure much difference to efficiency or duplicate computing because need to run the crude eitherway... 

Also, showing counts for each of the estimate calculations is also pretty common, though I guess could be done with some combo of gtsummary::tbl_cross, tbl_uvregression and tbl_merge? 

Thanks!

![image](https://user-images.githubusercontent.com/18347047/102622737-59c5ab00-4139-11eb-87d8-a8cc42974454.png)

**Comment by ddsjoberg** [comment] 2020-12-28 00:09
@asshah4 FYI, there is a draft of an `add_strata()` function in pull request #726. If you're familiar with GitHub branches, I'd love for you to review the function and provide feedback.

@aspina7 @mjrolland I am not sure if the version of the `add_strata()` function in pull request #726 will assist you in getting the tables you're looking for. I think you'll need to start with `tbl_cross()` and the function only works with `tbl_summary()` for now. I did write a small function, `tbl_cmh()`, to calculate the Cochran-Mantel-Haenszel OR and test. 

```r
library(gtsummary)
library(dplyr)

trial %>$
  select(exposure = response, case = death, grade, stage) %>%
  # creating a dataset with case-control and exposure status
  mutate(exposure = factor(exposure, labels = c("Not Exposed", "Exposed")),
         case = factor(case, labels = c("Control", "Case"))) %>%
  # calculating the CMH OR and tabling the results
  tbl_cmh(case = case, 
          exposure = exposure, 
          strata = c(grade, stage), 
          label = list(grade ~ "Tumor Grade"),
          overall_or = TRUE, 
          overall_label = "Overall") %>%
  # the table is a gtsummary object, so you can use add any general gtsummary function 
  bold_labels() %>%
  bold_p()
```

The code for the function is here https://gist.github.com/ddsjoberg/a12565f21142052ba5933ab1fc36a1ba

It returns a gtsummary table, which means you can use any of the general gtsummary functions on it, like `modify_header()`, `as_flex_table()`, `bold_labels()`, `tbl_merge()`, `tbl_stack()`, etc. If you wish to use the function, I recommend reviewing the accuracy of the code....I haven't calculate a CMH OR in many many years!

**Comment by asshah4** [comment] 2020-12-30 19:00
@ddsjoberg I'm glad to do so. Thank you for taking the time to consider the `add_strata()` function. I'll use that branch and see if it produces anything surprising. Great package, once again!

**Comment by ddsjoberg** [comment] 2020-12-30 19:05
> @ddsjoberg I'm glad to do so. Thank you for taking the time to consider the `add_strata()` function. I'll use that branch and see if it produces anything surprising. Great package, once again!

Thank you @asshah4 ! Much appreciated!

**Comment by asshah4** [comment] 2021-01-02 15:38
@ddsjoberg I've taken a look at the code thus far, and found the following areas. This isn't intended to be deconstructive - once again its a great addition to a great package. 

```r
library(gtsummary)
library(dplyr)
data(trial)

# Make data slightly more "messy"
df <- bind_rows(trial[1:5,], trial) %>%
	select(-ttdeath)
df$trt[1:5] <- NA
df$trt <- as.factor(df$trt)

# Simple table summmary
df %>%
	select(-ttdeath) %>%
	tbl_summary(
		by = trt,
		missing = "no"
	) %>%
	add_p()
```

This runs, and creates a small warning about observations being missing. The `by` argument doesn't through this error if the column class is `character()`. I bring this up as the current `add_strata()` function will repeat this warning. 

```
# Strata table
df %>%
	tbl_summary(
		by = trt,
		missing = "no"
	) %>%
	add_p() %>%
	add_strata(
		strata = grade,
		method = "merge"
	)
```

The things I notice that happened:

1. The original issue with the `by` argument is repeated
1. `add_strata` checks the `strata` argument and issues the same warning for each level of the variable. 
1. The column added by `add_p()` is dropped, which I wouldn't have expected from the `tbl_merge` component. This occurs if the method is `stack` instead of `merge` as well.

Next I looked at benchmarks for speed between the original described approach, and this one.  It looks to be 20-30% slower and we lose the columns we've added. 

``` r
# Benchmarking
library(microbenchmark)
library(gtsummary)
library(tidyverse)

microbenchmark(
    times = 5,
    "workaround" = {
        tbls <- 
            trial %>%
            group_by(grade) %>%
            nest() %>%
            rowwise() %>%
            mutate(tbl = list(tbl_summary(
                data,
                by = trt,
                missing = "no"
            ) %>%
                add_p()
            ))
        
        tbl_merge(tbls$tbl, tab_spanner = str_glue("**{tbls$grade}**"))
    },
    "add_strata" = {
        # Strata table
        trial %>%
            tbl_summary(
                by = trt,
                missing = "no"
            ) %>%
            add_p() %>%
            add_strata(
                strata = grade,
                method = "merge"
            )
    }
)
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(23, 31, 37, 31, 46, 52, 63, 37, 31, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(0.16, 0.277, 0.354, 0.144, 0.325, 0.719, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(24, 24, 24, 24, 24, 24, 24, 20.9, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(32, 47, 61, 38, 78, 36, 51, 39, 71, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(1.739, 0.266, 1.713, 0.096, 0.175, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(18.43, 24, 16.92, 23.89, 17.43, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(51, 38, 57, 48, 61, 54, 38, 36, 40, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(17.64, 16.43, 24, 24, 21.19, 12.1, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(23, 31, 37, 31, 46, 52, 63, 37, 31, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(0.16, 0.277, 0.354, 0.144, 0.325, 0.719, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(24, 24, 24, 24, 24, 24, 24, 20.9, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(32, 47, 61, 38, 78, 36, 51, 39, 71, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(1.739, 0.266, 1.713, 0.096, 0.175, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(18.43, 24, 16.92, 23.89, 17.43, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(51, 38, 57, 48, 61, 54, 38, 36, 40, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(17.64, 16.43, 24, 24, 21.19, 12.1, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(23, 31, 37, 31, 46, 52, 63, 37, 31, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(0.16, 0.277, 0.354, 0.144, 0.325, 0.719, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(24, 24, 24, 24, 24, 24, 24, 20.9, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(32, 47, 61, 38, 78, 36, 51, 39, 71, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(1.739, 0.266, 1.713, 0.096, 0.175, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(18.43, 24, 16.92, 23.89, 17.43, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(51, 38, 57, 48, 61, 54, 38, 36, 40, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(17.64, 16.43, 24, 24, 21.19, 12.1, : cannot compute exact p-value with ties
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(23, 31, 37, 31, 46, 52, 63, 37, 31, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(0.16, 0.277, 0.354, 0.144, 0.325, 0.719, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(24, 24, 24, 24, 24, 24, 24, 20.9, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(32, 47, 61, 38, 78, 36, 51, 39, 71, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(1.739, 0.266, 1.713, 0.096, 0.175, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(18.43, 24, 16.92, 23.89, 17.43, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(51, 38, 57, 48, 61, 54, 38, 36, 40, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(17.64, 16.43, 24, 24, 21.19, 12.1, : cannot compute exact p-value with ties
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Variable 'grade' is `NA` for all observations and cannot be summarized as 'categorical'.
#> Using `grade ~ "dichotomous"` instead.
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(23, 31, 37, 31, 46, 52, 63, 37, 31, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(0.16, 0.277, 0.354, 0.144, 0.325, 0.719, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(24, 24, 24, 24, 24, 24, 24, 20.9, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(32, 47, 61, 38, 78, 36, 51, 39, 71, : cannot compute exact p-value with ties
#> Warning for variable 'marker':
#>  simpleWarning in wilcox.test.default(x = c(1.739, 0.266, 1.713, 0.096, 0.175, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(18.43, 24, 16.92, 23.89, 17.43, 24, : cannot compute exact p-value with ties
#> Warning for variable 'age':
#>  simpleWarning in wilcox.test.default(x = c(51, 38, 57, 48, 61, 54, 38, 36, 40, : cannot compute exact p-value with ties
#> Warning for variable 'ttdeath':
#>  simpleWarning in wilcox.test.default(x = c(17.64, 16.43, 24, 24, 21.19, 12.1, : cannot compute exact p-value with ties
#> Unit: seconds
#>        expr      min       lq     mean   median       uq      max neval cld
#>  workaround 2.981080 2.983475 3.045436 3.058661 3.075328 3.128635     5  a 
#>  add_strata 3.645856 3.675003 3.723516 3.712544 3.770776 3.813403     5   b
```

<sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

One thought I had was to perhaps include the `strata` argument in the original `tbl_summary()` function, so the overhead of recomputing statistics would be lessened. That does end up with the same problem of which statistical tests to run, (e.g. pooled methods, individual strata statistics, etc). 

I don't know enough about R programming and pipes to know if the pipeline could also detect if `add_strata()` was available downstream, and then perform the function a bit differently. I know that error checking happens in a "last in, first out" method, so perhaps the infrastructure is available. This would allow something like `add_p()` to be positioned in two places (either before the `add_strata()` for individualized statistics, or after for pooled statistics).

Obviously I don't know the big picture here, as this function seems to be able to work for several times of objects.

**Comment by ddsjoberg** [comment] 2021-01-02 17:05
@asshah4 ! Thank you so much for the thorough review!  Your comments and ideas are MUCH appreciated, and they're great.  There are PROs and CONs to different approaches, and I'll try to describe them.

1. I am not sure what you mean about the note concnering missing `by=` values only prints for factor and not character. Below is an example with `trt` as character and factor with the same message.

    ``` r
    library(gtsummary)
    packageVersion("gtsummary")
    #> [1] '1.3.5.9019'
    
    # Make data slightly more "messy"
    df <- dplyr::bind_rows(trial[1:5,], trial) %>%
      select(-ttdeath)
    
    df$trt[1:5] <- NA
    df$trt_fct <- as.factor(df$trt)
    
    # trt as chr
    tbl1 <- df %>% select(trt, age) %>% tbl_summary(by = trt)
    #> 5 observations missing `trt` have been removed. To include these observations, use `forcats::fct_explicit_na()` on     `trt` column before passing to `tbl_summary()`.
    
    # trt as fct
    tbl2 <- df %>% select(trt_fct, age) %>% tbl_summary(by = trt_fct)
    #> 5 observations missing `trt_fct` have been removed. To include these observations, use `forcats::fct_explicit_na()`     on `trt_fct` column before passing to `tbl_summary()`.
    ```
    
    <sup>Created on 2021-01-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

1.  If you include `tbl_summary(include = -grade)` in the original call, you won't see any warning about missing grade. But I think this should be updated to users don't see these messages if they don't include the argument.

    ```{r}
    # Simple table summmary
    df %>%
      tbl_summary(
        by = trt,
        missing = "no",
        include = -grade
      ) %>%
      add_strata(grade)
    ```

1. You mentioned that you were surprised the p-value column was dropped. Yes, I agree...but it proved difficult to accurately search the call stack for the `add_p()` function and apply them in the same way to each of the tables within the strata.  There was difficulty because it can be called with piping (like you've done), but also with `t1 <- tbl_summary(trial, by = trt); t2 <- add_p(t1)`.  What I had done to try and make this work was add the argument `add_strata(additional_fn=)` to add more gtsummary calls, e.g. 
    ```r
    trial %>%
      select(age, grade, trt, stage) %>%
      mutate(grade = paste("Grade", grade)) %>%
      tbl_summary(by = trt, include = -grade, missing = "no") %>%
      add_strata(
        strata = grade,
        additional_fn = ~add_p(.x) 
      )
    ```
I don't know/think this was the best solution...but found it difficult to do something better.

1. Add and argument to `tbl_summary()`? I like that solution, but is comes with a severe limitation: the output is no longer a `tbl_summary()` object, rather it is a `tbl_merge()` obejct. Therefore, you cannot use functions, such as `add_p()` designed to work with `tbl_summary()` objects. I do like the syntax of `tbl_summary(by = c(by, strata))` and I think working toward something that could make this work would be great. There are two possible solutions I see immediately.
    1. We could add  `tbl_summary(by = c(by, strata), additional_fns = )` argument, but I don't like it...
    2. We could add methods `add_p.tbl_merge()` that would inspect the internals of the `tbl_merge()` object, then attempt to run `add_p.tbl_summary()` on each component table, then re-merge the tables.......I like the API this brings to the user....but requires quite a bit of work. There are also quite a few functions this would NOT work for, such as `modify_header()`....

1. Perhaps the best solution is to just add a new function `tbl_strata(data, additional_fns, method = c("tbl_summary"), ....)`. The function could stratify the results from `tbl_summary()`, `tbl_uvregression()`, `tbl_cross()`, etc.  This introduces some other issues, but would be a good general solution.

Anyway, these are just my initial thoughts! Will continue to think on it, and would love to hear your throughts.

**Comment by ddsjoberg** [comment] 2021-01-03 19:41
I made an update to remove the duplicated messages (I originally misunderstood what you meant about the repeating messages). I've also given more thought about the best approach.

  - I added a message to help users know that they can pass functions in the `additional_fn=` argument. This message will print 
    ``` r
    library(gtsummary)
    
    tbl <- 
      trial %>% 
      select(grade, trt, age) %>% 
      tbl_summary(by = trt) %>% 
      add_p() %>% 
      add_strata(grade)
    #> i Include the additional modifications to the stratified tables with
    #>   `additional_fn = ~.x %>% add_p()`
    ```
  - This solution has the benefit of applying all the formatting from the original `tbl_summary()` call to each of the stratified tables.

**Comment by asshah4** [comment] 2021-01-03 22:59
That's a great way to pass along those additional parameters! That also sounds like it has the flexibility to add functions in the future. I'll try this out in a current project and see how it holds up. 

I'll think on this as well - being able to add strata would be tremendously helpful for both regression and summary tables.

**Comment by aspina7** [comment] 2021-01-30 19:06
Hi thanks a lot for this and sorry for the late response. The `add_strata `function looks great. 
`tbl_cmh `also looks great but noticed that the reference groups are flipped (i.e. you want to be dividing cases by controls and exposed by unexposed) - see code example below (cant get reprex to work because doesnt seem to like `source_gist`. This [website ](https://sphweb.bumc.bu.edu/otlt/mph-modules/bs/bs704-ep713_confounding-em/BS704-EP713_Confounding-EM7.html#:~:text=And%2C%20using%20the%20same%20data,strata%20of%20the%20confounding%20factor.) while outdated looking gives a good explanation. 

```

library("dplyr")
library("epibuffet") ## install from https://github.com/R4EPI/epibuffet
library("gtsummary") 

## source tbl_cmh function 
devtools::source_url("gist.githubusercontent.com/ddsjoberg/a12565f21142052ba5933ab1fc36a1ba/raw/3b20b7d35eb6574953cb9bbb7a9e87edbef9d890/tbl_cmh.R")

                      
new_trial <- trial %>%
  # creating a dataset with case-control and exposure status
  select(exposure = response, case = death, grade, stage) %>%
  mutate(exposure = factor(exposure, labels = c("Not Exposed", "Exposed")),
         case = factor(case, labels = c("Control", "Case")), 
         grade_bin = factor(
           ifelse(grade %in% c("II", "III"), "High", "Low"), 
           levels = c("Low", "High")
           )) %>% 
  ## only keep variables of interest and make them binary 
  ## difficult to read in tables but so can compare directly with tab_univariate
  select(case, exposure, grade_bin) %>% 
  mutate(
    across(everything(),
           ~ifelse(.x %in% c("High", "Exposed", "Case"), TRUE, FALSE)
    ))

## using gtsummary function 
new_trial %>%
  # calculating the CMH OR and tabling the results
  tbl_cmh(case = case, 
          exposure = exposure, 
          strata = c(grade_bin), 
          label = grade_bin ~ "Tumor Grade",
          overall_or = TRUE, 
          overall_label = "Overall")

## for comparison with r4epis function 
new_trial %>% 
  epibuffet::tab_univariate(case, exposure, strata = grade_bin)

## for reference: calculating OR by hand
## overall (cases_exposed * controls_unexposed) / (controls_exposed * cases_unexposed)
(24 * 51) / (37 * 88)

## tumor grade false strata
(7 * 21) / (14 * 26)

## tumor grade true strata 
(17 * 30) / (23 * 62)

## cmh or 
## divide in each strata by the total in that strata (i.e. sum of the row in gtsummary output)
( ((7 * 21) / 68) + ((17 * 30) / 132) ) /
  ( ((14 * 26) / 68) + ((23 * 62) / 132))
```

**Closed** 2021-02-08 18:47 UTC

**Comment by ddsjoberg** [comment] 2021-02-08 18:51
FYI, I decided to go with a `tbl_strata()` function instead of `add_strata()`.

```r
trial %>%
  select(age, grade, stage, trt) %>%
  mutate(grade = paste("Grade", grade)) %>%
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~.x %>%
      tbl_summary(by = trt, missing = "no") %>%
      add_n()
  )
```

![image](https://user-images.githubusercontent.com/26774684/107267300-b1cfae00-6a14-11eb-9859-a4ac23c170f9.png)

**Comment by asshah4** [comment] 2021-02-08 19:01
I like it, and I thinks it's a good idea as it'll allow you to keep the
internals working.

I actually used the add_strata() for a formal presentation, and overall I'm
a huge fan.

Thanks for being so responsive!

**Comment by aspina7** [comment] 2021-02-12 07:11
@ddsjoberg sorry to bother - but if i have a go at updating your [gist](https://gist.github.com/ddsjoberg/a12565f21142052ba5933ab1fc36a1ba) would you consider integrating the cmh stuff as a function please? Or is it maybe worth trying to integrate an add_cmh to tbl_strata? 
Also understand if you think this is out of scope.... 
Thanks!

**Comment by ddsjoberg** [comment] 2021-02-12 14:22
hi @aspina7 !

Writing a `tbl_cmh()` function is the simple part. But if it is added to gtsummary, I will also need to maintain and support it for years to come. Unfortunately, I at the moment, I don't think I can take that on.

Does your organization have an R package repo? I am happy to submit a pull request adding a `tbl_cmh()` function to it.

**Comment by aspina7** [comment] 2021-02-13 08:19
hey @ddsjoberg, fair enough! 
Could you submit a pr to this [repo](https://github.com/R4EPI/epibuffet) please? then we would re-organise that repo to be a wrapper for gtsummary functions. Could you just take a look at my [last post](https://github.com/ddsjoberg/gtsummary/issues/679#issuecomment-770265316) on here please before submitting? 
Thanks so much for your help - really appreciated!
