### ISSUE TITLE
Feature request: `tbl_uvregression` method for `mice:mids` objects

### ISSUE THREAD

**Issue by jrob95** [ddsjoberg/gtsummary#2069] opened 2024-11-18 05:08 UTC
Firstly, thanks for all your hard work in developing this package, it is very very useful. 

I though I would add to the issue first brought up here: /issues/928
I have had a pretty sleep deprived crack at it over the past few days, and I'm very very green with metaprogramming so I don't know how helpful this will be.
I just added all of this in to `R/tbl_uvregression.R`

```
# method for mids objects
#' @export
#' @name tbl_uvregression
tbl_uvregression.mids <- function(data,
                                  y = NULL,
                                  x = NULL,
                                  method,
                                  method.args = list(),
                                  exponentiate = FALSE,
                                  label = NULL,
                                  include = everything(),
                                  tidy_fun = pool_and_tidy_mice,
                                  hide_n = FALSE,
                                  show_single_row = NULL,
                                  conf.level = 0.95,
                                  estimate_fun = ifelse(exponentiate, label_style_ratio(), label_style_sigfig()),
                                  pvalue_fun = label_style_pvalue(digits = 1),
                                  formula = "{y} ~ {x}",
                                  add_estimate_to_reference_rows = FALSE,
                                  conf.int = TRUE, ...) {
  set_cli_abort_call()
  y <- enquo(y)
  x <- enquo(x)
  method.args <- enquo(method.args)

  # all transformations done on original unimputed data..
  complete_data <- data$data

  # setting default values -----------------------------------------------------
  if (missing(pvalue_fun)) {
    pvalue_fun <-
      get_deprecated_theme_element("tbl_regression-arg:pvalue_fun") %||%
      get_theme_element("pkgwide-fn:pvalue_fun", default = pvalue_fun)
  }
  pvalue_fun <- as_function(pvalue_fun, arg = "pvalue_fun")

  check_scalar_logical(exponentiate)
  if (missing(estimate_fun)) {
    estimate_fun <-
      get_theme_element("tbl_regression-arg:estimate_fun", default = estimate_fun)
  }
  estimate_fun <- as_function(estimate_fun, arg = "estimate_fun")

  if (missing(conf.int)) {
    conf.int <- get_theme_element("tbl_regression-arg:conf.int", default = conf.int)
  }
  if (missing(conf.level)) {
    conf.level <- get_theme_element("tbl_regression-arg:conf.level", default = conf.level)
  }
  if (missing(add_estimate_to_reference_rows)) {
    add_estimate_to_reference_rows <-
      get_theme_element("tbl_regression-arg:add_estimate_to_reference_rows",
                        default = add_estimate_to_reference_rows)
  }

  # check inputs ---------------------------------------------------------------
  check_not_missing(method)
  check_scalar_logical(hide_n)
  check_scalar_logical(add_estimate_to_reference_rows)
  check_scalar_logical(conf.int)
  check_scalar_range(conf.level, range = c(0, 1))
  check_uvregression_formula(formula)

  # check that only one of arguments x and y is specified
  if ((!is_quo_empty(x) && !is_quo_empty(y)) || (is_quo_empty(x) && is_quo_empty(y))) {
    cli::cli_abort(
      "Must specify one and only one of arguments {.arg x} and {.arg y}.",
      call = get_cli_abort_call()
    )
  }


  # process inputs -------------------------------------------------------------
  x <- .process_x_and_y_args_as_string(complete_data, x)
  y <- .process_x_and_y_args_as_string(complete_data, y)
  check_scalar(x, allow_empty = TRUE)
  check_scalar(y, allow_empty = TRUE)


  cards::process_selectors(
    as.data.frame(complete_data),
    include = {{ include }},
    show_single_row = {{ show_single_row }}
  )

  # styler: off
  # remove any variables specified in arguments `x`/`y` from include
  include <- include |>
    setdiff(tryCatch(stats::reformulate(c(x, y)) |> all.vars(), error = \(e) character()))
  # remove any variables not in include
  show_single_row <-
    if (is_empty(x)) intersect(show_single_row, include)
  else intersect(show_single_row, x)
  #styler: on

  cards::process_formula_selectors(
    as.data.frame(complete_data)[include],
    label = label
  )
  cards::check_list_elements(
    x = label,
    predicate = \(x) is_string(x),
    error_msg = "Each value passed in the {.arg label} argument must be a string of length {.val {1}}."
  )

  .check_haven_labelled(as.data.frame(complete_data)[include])

  # fill in labels
  label <-
    map(include, ~label[[.x]] %||% attr(as.data.frame(complete_data)[[.x]], 'label') %||% .x) |>
    set_names(include)

  # will return call, and all object passed to in table1 call
  # the object func_inputs is a list of every object passed to the function
  tbl_uvregression_inputs <- as.list(environment())

  # construct models -----------------------------------------------------------
  lst_models <-
    include |>
    # construct a formula for each model
    .construct_uvregression_formulas(formula = formula, x = x, y = y) |>
    # build models
    .construct_uvregression_models_mids(data = data, method = method, method.args = !!method.args)


  # summarize each regression model with `tbl_regression()` --------------------
  lst_tbls <-
    lst_models |>
    .construct_uvregression_tbls(
      label = label, exponentiate = exponentiate, tidy_fun = tidy_fun,
      show_single_row = show_single_row, conf.level = conf.level,
      estimate_fun = estimate_fun, pvalue_fun = pvalue_fun,
      add_estimate_to_reference_rows = add_estimate_to_reference_rows,
      conf.int = conf.int, x = x, ...
    )

  # if the outcome varied, then replace the variable names within tbls
  if (is_empty(y)) {
    lst_tbls <- lst_tbls |>
      imap(
        function(tbl, variable) {
          tbl$table_body$variable <- variable
          tbl$table_body$var_type <- NA_character_
          tbl
        }
      )
  }

  # stacking results to return -------------------------------------------------
  results <- tbl_stack(lst_tbls)
  class(results) <- c("tbl_uvregression", "gtsummary")

  # update column header if `x=` was used --------------------------------------
  if (!is_empty(x)) {
    results <- modify_table_styling(results, columns = "label", label = "**Outcome**")
  }

  # removing modify_stat_* columns ---------------------------------------------
  results$table_styling$header <-
    results$table_styling$header %>%
    select(-starts_with("modify_stat_"))

  # adding column of N ---------------------------------------------------------
  # if (hide_n == FALSE) results <- add_n(results, location = "label") # styler: off

  # exporting results ----------------------------------------------------------
  results$inputs <- tbl_uvregression_inputs
  results$call_list <- list(tbl_uvregression = match.call())

  results
}
```

I also created two new helper functions and stole a function from cardx to make the call work.
```

# helper from cardx
.as_list_of_exprs <- function(x, arg_name = "method.args") {
  x_enexpr <- rlang::enexpr(x)
  if (is_call_simple(x_enexpr)) {
    return(call_args(x_enexpr))
  }

  cli::cli_abort(
    c("There was an error processing the {.arg {argname}} argument.",
      i = "Expecting a simple call. See {.help rlang::is_call_simple} for details."
    ),
    call = get_cli_abort_call()
  )
}


.construct_uvregression_models_mids <- function(formulas, data, method, method.args) {
  method.args <- enquo(method.args)
  imap(
    formulas,
    \(formula, variable) {
      # Use mice::with() to apply the formula and fit the model for each imputed dataset
      model_i <- mice_in_tbl_uvregression(data = data,
                                          method = method,
                                          formula = formula,
                                          method.args = !!method.args)
      model_i
    }
  )
}


mice_in_tbl_uvregression <- function(data,
                                     method,
                                     formula = NULL,
                                     method.args = NULL) {
  # set up the formula
  environment(formula) <- environment()
  formula_expr <- deparse(as.formula(formula))  # This converts the formula to text
  # use function from cardx to convert method args to list, which can then become text for glue function
  method.args <- .as_list_of_exprs({{ method.args }})

  # confirm method.args is a list, and then convert to text
  if (!is.null(method.args) && is.list(method.args)) {
    if (is.null(names(method.args))) {
      stop("method.args must be a named list, e.g., list(family = binomial(link = 'log'))")
    }

    # Extract the arguments from the list, ensuring they are named
    method_args_expr <- paste0(
      ", ",
      paste(
        sapply(seq_along(method.args), function(i) {
          arg_name <- names(method.args)[i]
          arg_value <- deparse(method.args[[i]])
          glue::glue("{arg_name} = {arg_value}")
        }),
        collapse = ", "
      )
    )
  } else {
    method_args_expr <- ""
  }

  # Construct the call expression
  fun_call <- parse(
    text = glue::glue(
      "with(data = {deparse(substitute(data))}, expr = {deparse(substitute(method))}(as.formula('{formula_expr}'){method_args_expr}))"
    )
  )
  # Evaluate the constructed call
  out <- eval(fun_call)
  out$call$expr[[2]] <- out$call$expr[[2]][[2]]
  out
  # Check if the result is a mira object
  if (inherits(out, "mira")) {
    return(out) 
  } else {
    stop("The result is not a mira object!")
  }
}

```

Additionally, I tried to do this on a fork this repo, which I would have then sent as a pull request, but the latest dev version was causing me error out the wazzoo, and I figure I could work off a stable version, which I couldn't figure out how to fork off so this seemed like my best compromise.  My apologies for the mess!

Sorry, I haven't worked to make any of the testing suite for this.
Hope this is useful.
Cheers,
Jack

**Comment by ddsjoberg** [comment] 2024-11-20 00:26
Hi @jrob95 , this looks like great work!

I know I have been open to a mids method for this function in the past, but now that I am looking down the barrel of maintaining it for the rest of my life...I am feeling some hesitation 😆 

Can you try implementing this in a separate package for now? Also, note that the method for survey data is simply equal to that for the standard data frame method.

```r
#' @export
#' @name tbl_uvregression
tbl_uvregression.survey.design <- tbl_uvregression.data.frame
```

I think we could get a `tbl_uvregression.mids` S3 method up and running somewhat easily with the following steps:
1. Create a `as.data.frame.mids()` S3 method that simply extracts the first data frame in a mids object. This is used by tidyselect to select columns.
2. Create a `cardx::construct_model.mids()` S3 method that takes in input the mids object, a method, formula, etc, and constructs the regression model. You can review the `cardx::construct_model.data.frame()` and `cardx::construct_model.survey.design()` methods for guidence.

If all it takes are these two steps, we can consider adding it to gtsummary. But let's do this development in a package you own for now.

**Comment by jrob95** [comment] 2024-11-22 02:16
Thanks @ddsjoberg,
Fair enough, it was a little mind bending to hack together, and to be completely honest, I'm not entirely statisfied that it is particularly reliable. I'll start looking in to your proposed ideas when I have capacity again. 

For now I'll just leave this here in case anyone else finds it useful.

Jack

**Comment by ddsjoberg** [comment] 2024-11-22 02:19
Ok, thanks for the update. I'll close this now since no one is working on it at the moment.

In the meantime, you can `lapply()` over the covariates, build the models, summarize with `tbl_regression()`, and end with a `tbl_stack()` to get the table you are after.

**Closed by ddsjoberg** 2024-11-22 02:19 UTC

**Comment by ddsjoberg** [comment] 2024-12-20 00:49
That's awesome, congratulations!

I took a quick look at the code. I presume that defining the S3 methods didn't work out?

1. Create a `as.data.frame.mids()` S3 method that simply extracts the first data frame in a mids object. This is used by tidyselect to select columns.
2. Create a `cardx::construct_model.mids()` S3 method that takes in input the mids object, a method, formula, etc, and constructs the regression model. You can review the `cardx::construct_model.data.frame()` and `cardx::construct_model.survey.design()` methods for guidance.
