### ISSUE TITLE
Adding glmtoolbox::glmgee to the list of supported GEE engines

### ISSUE THREAD

**Issue by adrianolszewski** [ddsjoberg/gtsummary#1981] opened 2024-09-17 01:41 UTC
Would you, please, consider adding the **glmtoolbox** package -mostly the **glmgee()** function- to make users aware of this new awesome package for GEE estimation?

This may be a very important information especially for biostatisticians in clinical trials, using GEE extensively on daily basis, not only for trials with binary endpoints. The glmtoolbox creates a new **solid standard** for GEE estimation in R, offering reliable estimation and lots of tools absent in other packages. And, unlike the geepack, it is actively maintained. In geepack some serious issues remain unfixed, the engine often crashes for unstructured covariance (+ _wave_ argument), which is a serious problem, and sometimes problematic fits aren't even warned about. While geepack is a very popular package and historically among the very first implementations (right after "gee"), nowadays there are new, reliable implementations with great additions.  And the **glmtoolbox** is one of them. I am using it at work on daily basis and I wouldn't replace it by anything else today. It's gaining popularity and is now officially supported also by the emmeans, insights and parameters packages.

I just checked and it seems that the glmgee class is handled by gtsummary, so IMO it's worth to announce it :)

**Comment by ddsjoberg** [comment] 2024-09-17 14:15
Dear @adrianolszewski , thanks for the post.

Great to hear that the package is already supported. @larmarange has written amazing code to support all regression models as long they are built with the standard model features, e.g. exports a methods like `model.frame()`, `model.matrix()`, `terms()`, etc.

@larmarange maintains a list of known functions/packages that are supported. https://larmarange.github.io/broom.helpers/reference/supported_models.html It looks like thsi issue is being tracked in broom.helpers already (https://github.com/larmarange/broom.helpers/issues/274, Nice!).

If you have R package development experience, I would think a pull request adding unit tests for broom.helpers to ensure support today and into the future. You could mimic the tests included for mmrm. See https://github.com/larmarange/broom.helpers/blob/main/tests/testthat/test-tidy_plus_plus.R

But we'll leave it up to @larmarange how they'd like to add support. Thanks both!

**Comment by larmarange** [comment] 2024-09-18 13:44
Yes it seems to work. The different methods are implemented. But as explained by @ddsjoberg  we need to add unit tests to `broom.helpers`.

If you could provide some models examples it would help.

**Comment by ddsjoberg** [comment] 2024-09-18 14:48
I am going to close this as it's been tracked in https://github.com/larmarange/broom.helpers/issues/274

**Closed by ddsjoberg** 2024-09-18 14:48 UTC
