### ISSUE TITLE
Bug Report: tbl_svysummary may generate inconsistent counts at margins/totals. Rounding errors?

### ISSUE THREAD

**Issue by philsf** [ddsjoberg/gtsummary#1150] opened 2022-02-15 02:50 UTC
Hi! I have found inconsistent behaviour in tbl_svysummary. When creating a contingency table in a [particular dataset](https://www.opm.gov/fevs/public-data-file/) the counts don't add up to the correct total. Could this behavior be caused due to when rounding is performed to create the table, so cell counts are rounded before adding table margins?

This is the table produced by tbl_svysummary:

```
svy <- svydesign(
  ids = ~1,
  data = analytical,
  weights = ~postwt)
svy %>%
  tbl_svysummary(
    include = q21,
    by = q1,
  ) %>%
  add_overall() %>% as_kable()
```

|**Characteristic** | **Overall**, N = 14,909 | **1**, N = 178 | **2**, N = 458 | **3**, N = 1,057 | **4**, N = 5,961 | **5**, N = 7,255 |
|:------------------|:-----------------------:|:--------------:|:--------------:|:----------------:|:----------------:|:----------------:|
|q21                |                         |                |                |                  |                  |                  |
|1                  |       148 (1.0%)        |    77 (44%)    |   45 (9.8%)    |    10 (0.9%)     |    11 (0.2%)     |    5 (<0.1%)     |
|2                  |       224 (1.5%)        |    38 (21%)    |    92 (20%)    |    45 (4.2%)     |    42 (0.7%)     |     8 (0.1%)     |
|3                  |       647 (4.3%)        |    21 (12%)    |   115 (25%)    |    251 (24%)     |    226 (3.8%)    |    35 (0.5%)     |
|4                  |       4,481 (30%)       |   15 (8.3%)    |   153 (33%)    |    507 (48%)     |   3,028 (51%)    |    779 (11%)     |
|5                  |       9,408 (63%)       |    27 (15%)    |    54 (12%)    |    245 (23%)     |   2,655 (45%)    |   6,428 (89%)    |

 Note the overall count of **14909**. I believe it sould be 14908, based on

1. manual sum of the row totals and
2. this raw table (total included = 14908.48).

```
> svytable(~q21 + q1, svy) %>% addmargins()
     q1
q21              1            2            3            4            5          Sum
  1      77.415772    44.845294     9.873744    10.780750     5.062258   147.977819
  2      37.502702    92.052689    44.599644    42.033213     7.593018   223.781267
  3      21.060355   114.961679   250.558380   225.821827    35.082694   647.484936
  4      14.793587   152.581270   507.097280  3027.525310   779.039010  4481.036457
  5      27.152097    53.758566   244.984706  2654.578024  6427.729257  9408.202650
  Sum   177.924513   458.199499  1057.113755  5960.739125  7254.506237 14908.483129
```

I can more or less reproduce the inconsistency in rounded totals when I round before/after adding the margins to the table:

```
> svytable(~q21 + q1, svy) %>% addmargins() %>% round()
     q1
q21       1     2     3     4     5   Sum
  1      77    45    10    11     5   148
  2      38    92    45    42     8   224
  3      21   115   251   226    35   647
  4      15   153   507  3028   779  4481
  5      27    54   245  2655  6428  9408
  Sum   178   458  1057  5961  7255 14908
```

```
> svytable(~q21 + q1, svy) %>% round() %>% addmargins()
     q1
q21       1     2     3     4     5   Sum
  1      77    45    10    11     5   148
  2      38    92    45    42     8   225
  3      21   115   251   226    35   648
  4      15   153   507  3028   779  4482
  5      27    54   245  2655  6428  9409
  Sum   178   459  1058  5962  7255 14912
```

As seen above, rounding before adding the margins gives an off-by-1 error in all row totals (225 instead of 224, 648 instead of 647...) which add up to an even greater discrepancy in the total (19412 instead of 14908).

Rounding only after margins gives both column totals and row totals that add to the grand total (in this case, 14908). Is this the way tbl_svysummary should work?

**Comment by philsf** [comment] 2022-02-15 02:52
Pre-processing of data is performed at https://github.com/philsf-biostat/SAR-2022-008-GJ/blob/main/scripts/input-raw.R

Cleaning and manipulations at https://github.com/philsf-biostat/SAR-2022-008-GJ/blob/main/scripts/input.R

**Comment by philsf** [comment] 2022-02-15 10:50
Note: I just found #1140, which may be related.

**Comment by ddsjoberg** [comment] 2022-02-15 13:31
thanks for the post @philsf !

can you make a reproducible example for me to run and test on my machine?

**Comment by philsf** [comment] 2022-02-15 14:17
Thanks for your response @ddsjoberg !

Not with this data (too large, too many manipulations, etc), but I am pretty sure I can reproduce the issue with the NHANES dataset as well.

I will give it a try later today and update the OP with the reprex.

**Comment by ddsjoberg** [comment] 2022-02-15 18:29
Thanks @philsf !

I can look into this something this week or next. My recollection is that we don't use `addmargins()`, rather re-run `svytable()`. Perhaps that is where the difference is coming into play.

If you'd like to take a look, the code for these calculations is in `r/tbl_svsummary.R`

**Comment by larmarange** [comment] 2022-02-16 20:15
I'm surprised. `tbl_svysummary()` keeps the exact values returned by `svytable()`. The rounding is performed when formatting the statistic (not before). Maybe something to due with #1140?

``` r
library(survey)
#> Le chargement a nécessité le package : grid
#> Le chargement a nécessité le package : Matrix
#> Le chargement a nécessité le package : survival
#> 
#> Attachement du package : 'survey'
#> L'objet suivant est masqué depuis 'package:graphics':
#> 
#>     dotchart
data(api)

dclus1 <- svydesign(id=~dnum, weights=~pw, data=apiclus1, fpc=~fpc)
tbl <- svytable(~ sch.wide + stype, dclus1)

tbl
#>         stype
#> sch.wide         E         H         M
#>      No   406.1640  101.5410  270.7760
#>      Yes 4467.8035  372.3170  575.3989

library(gtsummary)
dclus1 %>%
  tbl_svysummary(
    by = stype, include = sch.wide, 
    type = sch.wide ~ "categorical", 
    digits = ~ 1
  ) %>%
  add_overall(last = TRUE) %>%
  as_kable()
```

| **Characteristic** | **E**, N = 4,874 | **H**, N = 474 | **M**, N = 846 | **Overall**, N = 6,194 |
|:-------------------|:----------------:|:--------------:|:--------------:|:----------------------:|
| sch.wide           |                  |                |                |                        |
| No                 |   406.2 (8.3%)   | 101.5 (21.4%)  | 270.8 (32.0%)  |     778.5 (12.6%)      |
| Yes                | 4,467.8 (91.7%)  | 372.3 (78.6%)  | 575.4 (68.0%)  |    5,415.5 (87.4%)     |

<sup>Created on 2022-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment] 2022-02-16 20:35
Thanks @larmarange and @philsf !

I'll update the rounding before the next release for sure and replace the base R `round()` function. Regarding what it should be changed to....I like the idea of preserving the sum in the round, but I also like the idea of having very clear and obvious rounding rules (like the kind we learned in elementary school).

**Comment by larmarange** [comment] 2022-02-16 23:12
Thanks. I would say that the best would be to have both options, if
feasible, and to let users decide according to their specific needs.


Le mer. 16 févr. 2022 à 21:36, Daniel Sjoberg ***@***.***> a
écrit :

**Comment by philsf** [comment] 2022-02-18 15:48
Hi @larmarange and @ddsjoberg! Although there is definitly an issue in how `tbl_svysummary` presents the results (discrepancy around 8k in the NHANES example), I followed a suspicion that this overall rounding issue in surveys might not be as simple, [so I asked the interwebs](https://stats.stackexchange.com/questions/564422/contingency-table-under-complex-survey-design-yields-inconsistent-counts). The comment that I received indicates that the rounding discrepancy might not be a solvable in itself.

Here is how I understand the issue (please correct me if I'm wrong, as I am not an expert in surveys):

1. rounding frequencies from complex surveys might not be guaranteed to result in counts;
2. if 1 is true, we should expect an off-by-one error, in row totals and column totals;
3. if 1 and 2 are true, the totall discrepancy depends on the size of the table (degrees of freedom).

If everything above is true, then the best I could hope for `tbl_svysummary` to do is reproduce the **same** rounding error as `svytable`. 

What do you guys think?

**Comment by larmarange** [comment] 2022-02-18 15:59
Just a quick comment. `svytable()` do not round the cells. It simply computes the table using the weights.

When results are rounded, it's done later on by users. And as seen, applying `round()` before or after `addmargins()` do change the result.

**Comment by larmarange** [comment] 2022-02-18 16:13
Regarding NHANES, there are missing observations regarding the *Depressed* and the *HealthGen* variables.

The discrepancies come from the way `NA` are managed. It should maybe be investigated more.

Once we subset to full observations, the only differences are about rounding.

``` r
library(NHANES)
library(gtsummary)
library(survey)
#> Le chargement a nécessité le package : grid
#> Le chargement a nécessité le package : Matrix
#> Le chargement a nécessité le package : survival
#> 
#> Attachement du package : 'survey'
#> L'objet suivant est masqué depuis 'package:graphics':
#> 
#>     dotchart

nh <- svydesign(data = NHANESraw, strata = ~SDMVSTRA, id = ~SDMVPSU, nest = TRUE, weights = ~ I(WTMEC2YR/2))

svytable(~HealthGen + Depressed, nh) %>% sum()
#> [1] 204187210
svytable(~Depressed, nh) %>% sum()
#> [1] 204195559
svytable(~HealthGen, nh) %>% sum()
#> [1] 229852224

nh %>%
  tbl_svysummary(include = HealthGen, by = Depressed) %>%
  add_overall(last = TRUE) %>%
  as_kable()
#> 9779 observations missing `Depressed` have been removed. To include these observations, use `forcats::fct_explicit_na()` on `Depressed` column before passing to `tbl_svysummary()`.
```

| **Characteristic** | **None**, N = 158,758,609 | **Several**, N = 32,732,508 | **Most**, N = 12,704,441 | **Overall**, N = 204,195,558 |
|:-------------------|:-------------------------:|:---------------------------:|:------------------------:|:----------------------------:|
| HealthGen          |                           |                             |                          |                              |
| Excellent          |     21,327,182 (13%)      |      1,870,621 (5.7%)       |      563,613 (4.4%)      |       23,761,416 (12%)       |
| Vgood              |     57,487,318 (36%)      |       8,302,494 (25%)       |     1,855,865 (15%)      |       67,645,678 (33%)       |
| Good               |     59,920,032 (38%)      |      13,950,469 (43%)       |     4,698,948 (37%)      |       78,569,449 (38%)       |
| Fair               |     17,690,783 (11%)      |       7,355,105 (22%)       |     3,935,506 (31%)      |       28,981,393 (14%)       |
| Poor               |     2,324,945 (1.5%)      |      1,253,820 (3.8%)       |     1,650,510 (13%)      |       5,229,274 (2.6%)       |
| Unknown            |           8,349           |              0              |            0             |            8,349             |

``` r

nh2 <- nh %>%
  subset(!is.na(Depressed) & !is.na(HealthGen))

svytable(~HealthGen + Depressed, nh2) %>% sum()
#> [1] 204187210
svytable(~Depressed, nh2) %>% sum()
#> [1] 204187210
svytable(~HealthGen, nh2) %>% sum()
#> [1] 204187210

nh2 %>%
  tbl_svysummary(include = HealthGen, by = Depressed) %>%
  add_overall(last = TRUE) %>%
  as_kable()
```

| **Characteristic** | **None**, N = 158,750,260 | **Several**, N = 32,732,508 | **Most**, N = 12,704,441 | **Overall**, N = 204,187,209 |
|:-------------------|:-------------------------:|:---------------------------:|:------------------------:|:----------------------------:|
| HealthGen          |                           |                             |                          |                              |
| Excellent          |     21,327,182 (13%)      |      1,870,621 (5.7%)       |      563,613 (4.4%)      |       23,761,416 (12%)       |
| Vgood              |     57,487,318 (36%)      |       8,302,494 (25%)       |     1,855,865 (15%)      |       67,645,678 (33%)       |
| Good               |     59,920,032 (38%)      |      13,950,469 (43%)       |     4,698,948 (37%)      |       78,569,449 (38%)       |
| Fair               |     17,690,783 (11%)      |       7,355,105 (22%)       |     3,935,506 (31%)      |       28,981,393 (14%)       |
| Poor               |     2,324,945 (1.5%)      |      1,253,820 (3.8%)       |     1,650,510 (13%)      |       5,229,274 (2.6%)       |

<sup>Created on 2022-02-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by larmarange** [comment] 2022-02-18 16:15
@ddsjoberg : it seems that when `add_overall()` is applied, `NA` values from the `include` variable are excluded, however, the `NA` values from the `by` variable are not taken into account.

**Comment by ddsjoberg** [comment] 2022-02-18 18:43
> @ddsjoberg : it seems that when `add_overall()` is applied, `NA` values from the `include` variable are excluded, however, the `NA` values from the `by` variable are not taken into account.
@larmarange @philsf 

At the top of `tbl_svysummary()` (well, near-ish to the top, line 163), we exclude rows with missing `by=` levels (and signal to the users that these obs have been removed). We then save this subsetted data object internally, which is used by `add_overall.tbl_svysummary()`. Essentially, once these obs are removed, they are never used again in a subsequent gtsummary function that is called on the `tbl_svysummary()` table.

That said, do we think the deleted observations are contributing to any perceived discrepant numbers?

**Comment by ddsjoberg** [comment] 2022-02-20 12:18
@larmarange @philsf 

Thanks for helping us get to the bottom of this. Do we all agree any discrepancy we've illustrated here are due to the funny behavior with `round()` (which I'll address before the next release)?

**Comment by larmarange** [comment] 2022-02-20 17:37
> I think I am failing to see the issue here (also, I never use survey data, so forgive me if I am missing the obvious). Rows with missing by variables are dropped from `tbl_svysummary()`, which also means they are not included in the tabulations in `add_overall()`.

You are right. Sorry for my previous message which was ambiguous.

`tbl_svysummary()` does behave as expected. 

The only apparent discrepancies are due to a rounding effect as expressed in your previous message.

**Comment by ddsjoberg** [comment] 2022-02-20 17:43
Thanks @larmarange ! I don't think any comments were ambiguous :) We all posted so many tables, I was concerned I was missing something :)

@philsf  I am going to go ahead and close this. Please feel free to re-open if anything is left unaddressed!

**Closed by ddsjoberg** 2022-02-20 17:43 UTC

**Comment by philsf** [comment] 2022-02-20 18:10
Hi @ddsjoberg 

> @larmarange @philsf
> 
> Thanks for helping us get to the bottom of this. Do we all agree any discrepancy we've illustrated here are due to the funny behavior with `round()` (which I'll address before the next release)?

I agree that the off-by-one rounding error is probably within the theoretical realm of complex survey design and thus outside of the scope of gtsummary. I did not have the opportunity to run your last reprex on the NHANES data, so I don't understand why did I get such a large discrepancy and you did not.

However, in every way we have tried to slice the rounding of frequencies to approximate counts, we got different results. Maybe we shouldn't be trying to do this, at all? Here is what I propose: since the actual issue is due to the weights, maybe the default could be to present the tables without rounding to the nearest integers (just like larmarange's first example) and instead present the result with default `digits`?

Would this be a reasonable default?

**Comment by larmarange** [comment] 2022-02-20 18:28
> I don't understand why did I get such a large discrepancy and you did not.

The discrepancy you are referring to concerts the total N in the header of the table.

In a table produced by `tbl_svysummary()`, and this is the expected behaviour, if there are `NAs` in the `by` variable, they are dropped from the table and you have a message displayed in the console to warn you.

Regarding `NA` values in any of the variables defined in `include`: `NA` are excluded from the computation of percentages but the number of missing observations are displayed (by default) in an _unknown_ row. Please note that they could be several variables in `include`.

The number of observations displayed by default in the header / column title, is the total number of observations (missing values in `by` excluded, **but** missing values in any variable of `include` included).

When you perform `svytable()`, all missing values are by default excluded. If you want to reproduce this behaviour with `tbl_svysummary()`, you have to excluded missing values before calling `tbl_svysummary()`
