### ISSUE TITLE
tbl_summary fails because it cannot print "frailty" line from shared frailty model

### ISSUE THREAD

**Issue by proshano** [ddsjoberg/gtsummary#575] opened 2020-07-16 23:37 UTC
Please do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the gtsummary tag.

Hello,

I have noticed the following behaviour with coxph using the frailty term: If there is >1 independent variable, the following error is produced:

There was an error calling `broom::tidy(x, conf.int = TRUE)`,
  which is required for gtsummary to print the model summary.
  See error message below. 
Error: Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 3, 2

The problem is reproducible in other datasets.

```r
#this works fine
tbl_regression(coxph(Surv(time, status) ~ age + frailty(inst, df=4), lung), exponentiate = TRUE)

#this does not
tbl_regression(coxph(Surv(time, status) ~ age + sex + frailty(inst, df=4), lung), exponentiate = TRUE)

```
x There was an error calling `broom::tidy(x, conf.int = TRUE)`,
  which is required for gtsummary to print the model summary.
  See error message below. 
Error: Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 3, 2

**Comment by ddsjoberg** [comment] 2020-07-17 13:48
Hi @proshano ! Thank you for the comment! I have yet to try gtsummary with a frailty component.

The `tbl_regression()` function uses the `broom::tidy()` in the background to perform the initial prepping of the output. You indicated the smaller model works, but on my machine even the reduced model fails with `broom::tidy()` (see below). Can you provide more details about your environment? What version of broom and gtsummary do you have installed. Also, please do share your output using the [reprex](https://reprex.tidyverse.org/) package.

``` r
library(gtsummary)
#> Warning: package 'gtsummary' was built under R version 4.0.2
library(survival)
#> Warning: package 'survival' was built under R version 4.0.2
packageVersion("gtsummary")
#> [1] '1.3.2'
packageVersion("survival")
#> [1] '3.2.3'
packageVersion("broom")
#> [1] '0.5.6'

m1 <- coxph(Surv(time, status) ~ age + frailty(inst, df=4), lung) 
summary(m1)
#> Call:
#> coxph(formula = Surv(time, status) ~ age + frailty(inst, df = 4), 
#>     data = lung)
#> 
#>   n= 227, number of events= 164 
#>    (1 observation deleted due to missingness)
#> 
#>                       coef    se(coef) se2      Chisq DF   p    
#> age                   0.01937 0.009328 0.009254 4.31  1.00 0.038
#> frailty(inst, df = 4)                           3.33  3.99 0.500
#> 
#>     exp(coef) exp(-coef) lower .95 upper .95
#> age      1.02     0.9808     1.001     1.038
#> 
#> Iterations: 3 outer, 10 Newton-Raphson
#>      Variance of random effect= 0.03795014   I-likelihood = -743.6 
#> Degrees of freedom for terms= 1 4 
#> Concordance= 0.58  (se = 0.58 )
#> Likelihood ratio test= 9.96  on 4.97 df,   p=0.08
broom::tidy(m1, conf.int = TRUE)
#> Error in if (s$used.robust) {: argument is of length zero
tbl_regression(m1, exponentiate = TRUE)
#> x There was an error calling `broom::tidy(x, conf.int = TRUE)`,
#>   which is required for gtsummary to print the model summary.
#>   See error message below.
#> Error: Error in if (s$used.robust) {: argument is of length zero
```

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment] 2020-07-18 13:45
Hi @proshano ! It looks like there is a bug in `broom::tidy()` for Cox models with a frailty term https://github.com/tidymodels/broom/issues/899 .

I am going to go ahead and close this issue for now.  When the bug is fixed in broom, please to re-open or re-post this issue if the problem persists with gtsummary.

Happy Coding! 👯

**Closed by ddsjoberg** 2020-07-18 13:45 UTC

**Comment by proshano** [comment] 2020-07-18 15:40
Thank you!

Pavel
