### ISSUE TITLE
Feature request: Journal theme for APA-style tables

### ISSUE THREAD

**Issue by gorkang** [ddsjoberg/gtsummary#1145] opened 2022-02-08 09:38 UTC
Following @ddsjoberg  suggestion [here](https://stackoverflow.com/questions/71019853/there-is-a-way-to-add-a-column-with-the-test-statistics-in-gtsummarytbl-regres), I am opening this feature request.

A common style requirement for lots of psychology journals is the [Americal Psychological Association-style](https://apastyle.apa.org/products/publication-manual-7th-edition?tab=4) (APA-Style). This is used for all elements in papers, including formatting, tables, stats reporting, citations, etc.

In their website, they have:

- Table setup information: https://apastyle.apa.org/style-grammar-guidelines/tables-figures/tables
- Sample tables: https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables
  + With a [demographic characteristics table](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables#demographic), a [regression table](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables#regression), [ANOVA table](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/sample-tables#anova), etc.  

In the [Publication Manual of the American Psychological Association](https://apastyle.apa.org/products/publication-manual-7th-edition?tab=4) there are more examples and some alternatives (e.g. regression table with CI between brackets in a single column, hierarchical regression, etc.).

Maybe this may be a good place to start.

**Comment by ddsjoberg** [comment] 2022-02-08 16:11
Great, this is what I am seeing

1. **Cohort Summary Table** 
    - categorical variables: the APA uses one column for N and another for percent. While it's possible to construct these tables using gtsummary, it's not something that can be controlled with themes. 
    - Continuous variables: there is one column for Mean and another for SD. Again, while possible, cannot be controlled by themes. We can use themes to make the default statistic the Mean and SD.
    - tables with tests: it seems that it's common to report the test statistic, degrees of freedom, standardized mean difference, and p-value. The SMD and p-value is no issue. The test statistic is no issue, BUT we don't know internally whether is a t-, z-, chi- statistic, for example. The summaries for these methods are returned from `broom::tidy(t.test(...))` and the data frame has a column called statistic, but no label as to what the statistic type is.

2. **Regression Model Summary**
    - we can report the SE using themes
    - we can report the CI in two columns using themes
    - we can change the default labels for CI, p-values using themes
    - the example on the website isn't showing the test statistic. is this something that should be shown by default.

![image](https://user-images.githubusercontent.com/26774684/153027505-0755a737-a72f-4811-adec-f1a8440fdda8.png)

**Comment by ddsjoberg** [comment] 2022-02-17 21:03
Since we can't use themes to create APA summary tables, maybe we should just make an APA gtsummary pkg. We could export functions like `tbl_apa_summary()` and `tbl_apa_regression()`? I'd be happy to help you write it, if it's something you're interested in taking on.

**Comment by gorkang** [comment] 2022-02-21 13:50
This is a great idea @ddsjoberg ! But right now it would be impossible for me to take this on. Maybe in a few months time, I'll take your offer :)

Thanks!

**Comment by ddsjoberg** [comment] 2022-02-21 13:57
@gorkang sounds good!

**Comment by ddsjoberg** [comment] 2022-03-10 13:00
@gorkang i am going to close this issue for now.

whenever you're ready to pick it up again, please re-open and we can make a plan together :)

**Closed by ddsjoberg** 2022-03-10 13:00 UTC
