### ISSUE TITLE
Error when using tbl_summary with odd-values in character variable with a non-character "by" variable

### ISSUE THREAD

**Issue by ltin1214** [ddsjoberg/gtsummary#1889] opened 2024-08-05 14:20 UTC
This bug is in relation to gtsummary 2.0.0 and is not a problem in gtsummary 1.7.2

When a variable with the below strings as values is included in tbl_summary with a non-character "by" variable, there is an error related to dplyr::mutate stating "glue cannot interpolate functions into strings. * object 'n' is a function." 

```r
library(tidyverse)
library(gtsummary)
 
trial %>% 
  mutate(
    #Confirm issue is resolved when we use stage as a character variable: 
    #stage = as.character(stage), 
    trt = case_when(
      trt == "Drug A" ~ "Bladder + RP LN",
      TRUE ~ "Bladder + Renal Fossa",
    )
  ) %>% 
  tbl_summary(by = stage)

```
![bug when testing gtsummary 2 0 0](https://github.com/user-attachments/assets/3ab936df-5e6a-4a0e-877e-d7c8015a8627)

**Comment by ddsjoberg** [comment] 2024-08-05 18:26
Thank you for letting me know @ltin1214 !!

The issue is with a difference in the sort order from base R and `dplyr::arrange()`. For the time being, if you convert your stratifying variable to a character instead of factor, the code will run without issue. Although, this could result in your columns being in the incorrect order 🤷🏼‍♂️ 

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.0'

df_trt <- trial |> 
  dplyr::mutate(
    #Confirm issue is resolved when we use stage as a character variable: 
    #stage = as.character(stage), 
    trt = dplyr::case_when(
      trt == "Drug A" ~ "Bladder + RP LN",
      TRUE ~ "Bladder + Renal Fossa",
    )
  ) 

# show the discrepancy in sorting
df_trt |> dplyr::distinct(trt) |> dplyr::arrange(trt)
#> # A tibble: 2 × 1
#>   trt                  
#>   <chr>                
#> 1 Bladder + RP LN      
#> 2 Bladder + Renal Fossa
df_trt |> dplyr::distinct(trt) %>% {.[order(.$trt), ]}
#> # A tibble: 2 × 1
#>   trt                  
#>   <chr>                
#> 1 Bladder + Renal Fossa
#> 2 Bladder + RP LN

# make stage a character first and it will work
df_trt |> 
  dplyr::mutate(stage = as.character(stage)) |> 
  tbl_summary(
    include = trt,
    by = stage
  ) |> 
  as_kable()
```

| **Characteristic**    | **T1** N = 53 | **T2** N = 54 | **T3** N = 43 | **T4** N = 50 |
|:----------------------|:-------------:|:-------------:|:-------------:|:-------------:|
| trt                   |               |               |               |               |
| Bladder + Renal Fossa |   25 (47%)    |   29 (54%)    |   21 (49%)    |   27 (54%)    |
| Bladder + RP LN       |   28 (53%)    |   25 (46%)    |   22 (51%)    |   23 (46%)    |

<sup>Created on 2024-08-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment] 2024-08-08 04:51
Thanks again for the report @ltin1214 . This is now fixed in dev

**Closed by ddsjoberg** 2024-08-08 04:51 UTC
