### ISSUE TITLE
use flextable::as_flextable

### ISSUE THREAD

**Issue by davidgohel** [ddsjoberg/gtsummary#462] opened 2020-04-22 22:31 UTC
Hi, 

Many thanks for your time on this great project. 

I have noticed after having reading Peter Higgins on twitter 

> Turns out it helps to library(gtsummary) after library(flextable). Learning!

You could use the generic function from flextable [`flextable::as_flextable`](https://davidgohel.github.io/flextable/reference/as_flextable.html) to get rid of that constraint: 
 https://github.com/ddsjoberg/gtsummary/blob/ed70367f775213364643f4ecf81f8fea66dea044/R/as_flextable.R#L43

**Comment by ddsjoberg** [comment] 2020-04-23 03:22
Hi @davidgohel !!  Thank you so much for taking a look! 

I had originally imported the flaxtable's `as_flextable()`.  But I had some issues with the {gdtools} installation on macOS.  It seemed there was an additional software requirement for the installation to complete without error. (I don't recall exactly at the moment, but I think it was X11 or XQuartz?)  I added flextable as a `Suggests:` rather than `Depends:` because the `as_flextable()` function is still experimental, and I didn't want to possibly introduce installation issues.

Have you had any issues depending on the {gdtools} package?  If not, I will gladly import the flextable generic `as_flextable()`!

**Comment by davidgohel** [comment] 2020-04-28 08:45
Hi,

Yes, some users reported issues when trying to install gdtools from source. `gdtools` old version require XQuartz and new version requires package `systemtools` that requires XQuartz, I think R for mac requires XQuartz however... The new R will make things easier - not sure X11/XQuartz will still be required with the new toolchain. 

I will try to make gdtools dependency optional (from `Imports` to `Suggests`) in the following releases.

**Comment by higgi13425** [comment] 2020-06-18 16:10
Vignette example
Currently not working in R 3.6.2 or R 4.0.0

```{r}
trial %>%
  select(trt, age, grade) %>%
  tbl_summary(by = trt) %>%
  add_p() %>%
  as_flextable()
```

Error in UseMethod("as_flextable") : no applicable method for 'as_flextable' applied to an object of class "c('tbl_summary', 'gtsummary')"

**Comment by ddsjoberg** [comment] 2020-06-18 16:26
Hello @higgi13425 !

My guess is that the flextable package is loaded after gtsummary in this example?  The problem is that both {gtsummary} and {flextable} export an `as_flextable()` function.  When you load flextable after gtsummary, the gtsummary version is masked.

@davidgohel and I are working to get the issue resolved (https://github.com/davidgohel/flextable/issues/215) (well, mostly David, but if I can help let me know!).  When the PR for https://github.com/davidgohel/flextable/issues/215 is merged, I can update gtsummary to use the same `as_flextable()` generic as in the flextable package eliminating the issue.

In the meantime, you can directly specify the version from gtsummary  with `gtsummary::` to avoid the error:

```r
library(gtsummary)
library(flextable)
trial %>%
  select(trt, age, grade) %>%
  tbl_summary(by = trt) %>%
  add_p() %>%
  gtsummary::as_flextable()
```
![image](https://user-images.githubusercontent.com/26774684/85046703-c6e28e80-b15e-11ea-9cfa-3ba204b1975a.png)

**Comment by davidgohel** [comment] 2020-06-18 16:32
Hi, 

I am not working on it right now (busy with my company and my children sorry!) I will in July. 

PS: since a lot of issues in systemfonts have been solved I am not sure the initial motivation for making gdtools optional is still necessary.

**Comment by ddsjoberg** [comment] 2020-06-24 02:39
Now importing as_flextable from flextable

**Closed** 2020-06-24 02:59 UTC
