### ISSUE TITLE
Survey/Srvyr Support

### ISSUE THREAD

**Issue by barthelmes** [ddsjoberg/gtsummary#510] opened 2020-05-29 06:19 UTC
Dear Daniel Sjoberg and contributors,
thank you for developing this awesome package to finally deliver a table one straight from R!
The only thing that keeps me stuck with (the also great but not tidy) tableone package is propensity score matching and weighted analyses. 

_Enhancement suggestion:_ If you could add support for survey design objects and svyglm, svyttest in fashion of the tableone package, I could use and recommend your package even more frequently.

In any case, thanks for your work!
Best, 
-Jens

**Comment by ddsjoberg** [comment] 2020-05-29 12:34
Hi @barthelmes ! Thank you for the suggestion!  I agree with you 100% and this is a feature should be implemented.  There is an open issue for this feature #460.

I don't use survey methods, and after some reading, I am convinced I am not the one to write the function. (I wouldn't want to implement something incorrectly due to my in experience with the topic!) If you're interested, we can work together to implement :)

I think `tbl_regression()` works well with `svyglm()` results. If it does not, please do let me know!

I am going to close this issue, and continue to track this feature request at #460. Please feel free to continue the conversation on that issue!

Happy Coding!

**Closed by ddsjoberg** 2020-05-29 12:34 UTC
