### ISSUE TITLE
tbl_regression Statistical errors occur if hide_n is used

### ISSUE THREAD

**Issue by ltj-github** [ddsjoberg/gtsummary#1630] opened 2024-04-30 16:55 UTC
Statistical errors occur when I use the following formula, confidence intervals and p-values do not match, and if hide_n=T is removed it is fine
```r
tbl_regression(A,exponentiate = T,hide_n=T)
```
with hide_n=T
![image](https://github.com/ddsjoberg/gtsummary/assets/56884953/7ae74ea2-da69-4a30-9d2a-2a9938c6a7b0)

 removed
 
![image](https://github.com/ddsjoberg/gtsummary/assets/56884953/1dbb9630-7c9a-4bc3-a70b-25f431cccc7c)

**Comment by ddsjoberg** [comment] 2024-04-30 17:41
Thanks for the post @ltj-github ,

Can you please update your post with a reproducible example, aka a reprex. A reprex includes both data and code I can run on my machine that replicates your finding. Make the example as short as possible: the minimal amount of code to reproduce your finding and nothing more.

Take just a few minutes to review [reprex.tidyverse.org](https://reprex.tidyverse.org/) for detailed instructions on how to create a reprex.

**Comment by ddsjoberg** [comment] 2024-04-30 18:01
FYI, I ran a quick reprex without issue. I am going to go ahead and close this issue for now. But please re-open after you add your reprex, and we can investigate further

``` r
library(survival)
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.2'

mod <- coxph(Surv(time, status) ~ sex, data = lung)

# NOTE that hide_n is NOT an argument of this function, which is why we see a failure below
tbl_regression(mod, exponentiate = TRUE, hide_n = TRUE) |> as_kable()
#> ! `broom::tidy()` failed to tidy the model.
#> ✔ `tidy_parameters()` used instead.
#> ℹ Add `tidy_fun = broom.helpers::tidy_parameters` to quiet these messages.
```

| **Characteristic** | **HR** | **95% CI** | **p-value** |
|:-------------------|:------:|:----------:|:-----------:|
| sex                |  0.59  | 0.42, 0.82 |    0.001    |

``` r
tbl_regression(mod, exponentiate = TRUE) |> as_kable()
```

| **Characteristic** | **HR** | **95% CI** | **p-value** |
|:-------------------|:------:|:----------:|:-----------:|
| sex                |  0.59  | 0.42, 0.82 |    0.001    |

<sup>Created on 2024-04-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Closed by ddsjoberg** 2024-04-30 18:01 UTC

**Comment by ltj-github** [comment] 2024-05-01 02:51
```{r}

if (!requireNamespace("survey", quietly = TRUE)) install.packages("survey")
if (!requireNamespace("survival", quietly = TRUE)) install.packages("survival")
if (!requireNamespace("gtsummary", quietly = TRUE)) install.packages("gtsummary")

library(survey)
library(survival)
library(gtsummary)

set.seed(123)


data <- data.frame(
  Sdmvpsu = sample(1:3, 2757, replace = TRUE, prob = c(0.5, 0.4, 0.1)),  
  Sdmvstra = sample(59:148, 2757, replace = TRUE),  
  Age = round(runif(2757, 20, 80)),  
  Sex = sample(c("Male", "Female"), 2757, replace = TRUE, prob = c(0.5, 0.5)),  
  Race = sample(c("Non-hispanic black", "Non-hispanic white", "Other/multiracial", "Mexican american", "Other hispanic"),
                2757, replace = TRUE, prob = c(499, 1302, 246, 431, 279)/2757),  
  weight = round(runif(2757, 1775, 130302)),  
  level = sample(c("Deficient", "Insufficient", "Sufficient"), 2757, replace = TRUE, prob = c(90, 233, 2434)/2757)  
)

data$Time <- with(data, ifelse(level == "Deficient",
                               rexp(2757, rate = 0.05),
                               ifelse(level == "Insufficient",
                                      rexp(2757, rate = 0.03),
                                      rexp(2757, rate = 0.02))))
data$Mortstat <- with(data, ifelse(level == "Deficient",
                                   rbinom(2757, size = 1, prob = 0.5),
                                   ifelse(level == "Insufficient",
                                          rbinom(2757, size = 1, prob = 0.3),
                                          rbinom(2757, size = 1, prob = 0.1))))


summary(data)


design <- svydesign(
  data = data,
  ids = ~Sdmvpsu,
  strata = ~Sdmvstra,
  nest = TRUE,
  weights = ~weight,
  survey.lonely.psu = "adjust"
)


result <- svycoxph(Surv(Time, Mortstat) ~ level + Age + Sex + Race, design = design)

tbl_regression(result, exponentiate = TRUE, hide_n = TRUE)

tbl_regression(result, exponentiate = TRUE)
`

![image](https://github.com/ddsjoberg/gtsummary/assets/56884953/fd798ea3-e7b0-4b2e-86e5-dd05329a977b)
![image](https://github.com/ddsjoberg/gtsummary/assets/56884953/4da241f8-d7b1-4c67-9294-e79129541c66)

**Comment by ltj-github** [comment] 2024-05-01 02:53
Hello, this is the sample code I have created. You can give it a try. I am using method of svydesign.

**Comment by ddsjoberg** [comment] 2024-05-01 03:45
@ltj-github thanks for updating with a reproducible example.

The underlying issue is that you're using an argument, `hide_n`, that is **not** a part of the `tbl_regression()` object. You can see in the output that an error occurs:
```
! `broom::tidy()` failed to tidy the model.
```

When the default tidier fails (due to the incorrect code passed to it), we try using a tider from the {parameters} package.

```
✔ `tidy_parameters()` used instead.
ℹ Add `tidy_fun = broom.helpers::tidy_parameters` to quiet these messages.
```

It seems the parameters package tidier doesn't support your model type, and unfortunately, it fails while providing incorrect results. The good news is that if you correct the syntax, you won't have a problem. You could go further and post an issue to the parameters package using their tidier with your model showing the results `parameters::model_parameters()`.

**Comment by ltj-github** [comment] 2024-05-01 03:49
Thank you for your reply!
