### ISSUE TITLE
Error during knit if root dir is changed

### ISSUE THREAD

**Issue by GuiMarthe** [ddsjoberg/gtsummary#447] opened 2020-04-15 15:34 UTC
It appears that `tbl_summary` writes to disk during its call, although I haven't been able to find it in the code. 

A minimal example that I could recreate is to have an Rmd file like (sorry for the indent, I couldn't figure out a better way to represent the entire file):

```
	---
	title: "test"
	output: html_document
	---
	
	```{r setup}
	knitr::opts_knit$set(root.dir = '../')
	```
	
	```{r here}
	library(gtsummary)
	library(dplyr)
	gtsummary::trial %>% 
		select(trt, age) %>% 
		tbl_summary()
	```
```
And have the Rmd file located in:

```
test/
    notebooks/
         test.Rmd
 ```

When trying to knit the code chunk `here` will trigger the following error message:

```
processing file: test.Rmd
  |..............                                                        |  20%
  ordinary text without R code

  |............................                                          |  40%
label: setup
  |..........................................                            |  60%
  ordinary text without R code

  |........................................................              |  80%
label: here

Quitting from lines 11-16 (test.Rmd) 
Error in readLines(con, warn = FALSE) : cannot open the connection
Calls: <Anonymous> ... <Anonymous> -> enumerate_output_formats -> read_utf8 -> readLines
Execution halted
```

The issue does not happen in `gt`.

**Comment by GuiMarthe** [comment] 2020-04-15 15:37
This is the output of `sessionInfo()`

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8        LC_COLLATE=en_US.utf8      LC_MONETARY=pt_BR.UTF-8   
 [6] LC_MESSAGES=en_US.utf8     LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.3     gtsummary_1.2.6

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       rstudioapi_0.10  knitr_1.26       magrittr_1.5     munsell_0.5.0    tidyselect_1.0.0 gt_0.1.0         colorspace_1.4-1 R6_2.4.1        
[10] rlang_0.4.5      stringr_1.4.0    tools_3.6.3      grid_3.6.3       packrat_0.5.0    checkmate_1.9.4  gtable_0.3.0     xfun_0.11        commonmark_1.7  
[19] htmltools_0.4.0  ellipsis_0.3.0   digest_0.6.23    lazyeval_0.2.2   assertthat_0.2.1 tibble_2.1.3     lifecycle_0.1.0  crayon_1.3.4     purrr_0.3.3     
[28] ggplot2_3.2.1    tidyr_1.0.0      sass_0.1.2.1     vctrs_0.2.4      glue_1.3.1       stringi_1.4.5    compiler_3.6.3   pillar_1.4.2     backports_1.1.5 
[37] scales_1.1.0     forcats_0.4.0    pkgconfig_2.0.3 
```

**Comment by ddsjoberg** [comment] 2020-04-15 15:43
Hi @GuiMarthe !  Thank you for the report!

Can you please do me a favor, and confirm the issue persists if you simply print a table with the gt package.
For example, use `trial %>% gt::gt()` instead of `trial %>% select(trt, age) %>% tbl_summary()`.

gtsummary doesn't write to disk on it's own.  Rather, it creates a summary table, then prints the table using the gt package.

**Comment by ddsjoberg** [comment] 2020-04-15 15:54
FYI, I don't use the `root.dir` option in my own work.  But when I run this code, and the Rmd file is saved in `C:/Users/sjobergd/Desktop/test/my new project folder/subfolder` the file knits properly.

````
---
title: "test"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = 'C:/Users/sjobergd/Desktop/test/my new project folder/')
```

```{r here}
library(gtsummary)
library(dplyr)
gtsummary::trial %>% 
	select(trt, age) %>% 
	tbl_summary()
```
````

**Comment by ddsjoberg** [comment] 2020-06-22 01:32
Hello @GuiMarthe ! Could you please update and let me know if you're still experiencing the issue? Thanks!

**Comment by ddsjoberg** [comment] 2020-06-29 14:27
Hello there! I am going to go ahead and close this issue for now. But if you still experience the issue, please feel free to re-open!

**Closed by ddsjoberg** 2020-06-29 14:27 UTC

**Comment by nbarrowman** [comment] 2022-12-05 21:52
The problem is still there. I am using the `root.dir` option in knitr (I need it because I am using `knit_child` and need to specify the directory) and I get the error.

Thanks.

**Comment by ddsjoberg** [comment] 2022-12-05 21:55
@nbarrowman please post a new issue with a full reproducible example
