### ISSUE TITLE
Add significance stars in gtsummary on an anova

### ISSUE THREAD

**Issue by jordan49er** [ddsjoberg/gtsummary#1320] opened 2022-08-19 07:41 UTC
Is it possible to add significance stars on a gtsummary rendered table, with an anova ? I saw that it is possible with a regression, but I can't find any info on an anova. I'm trying to have stars appear next to the p values.
https://stackoverflow.com/questions/73403561/add-significance-stars-in-gtsummary-on-an-anova

**Comment by ddsjoberg** [comment] 2022-08-19 13:39
thanks for the post @jordan49er ! I think i can add this. It'll be on the list of features to implement.

**Comment by ddsjoberg** [comment] 2022-09-06 23:11
@jordan49er where do you want to see the stars? in the regression summaries, the p-values are removed and replaced with stars (by default).

**Comment by jordan49er** [comment] 2022-09-07 07:36
@ddsjoberg It would be best if the p-values were indeed removed and replaced by stars, as shown in this example : https://stackoverflow.com/questions/70539605/how-to-add-significance-stars-on-p-value-produced-by-add-glance-table-gtsummary
Thank you for your help !

**Comment by ddsjoberg** [comment] 2022-09-10 01:09
@jordan49er does this due what you need?

``` r
library(gtsummary)

tbl <-
  trial %>%
  tbl_summary(
    by = grade, 
    include = c(age, marker),
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  add_p(test = everything() ~ "aov") %>%
  add_significance_stars()
```
![image](https://user-images.githubusercontent.com/26774684/189462653-00574f55-2fb8-418c-acd2-462921854176.png)

<sup>Created on 2022-09-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

You can test the function from this branch 
https://github.com/ddsjoberg/gtsummary/pull/1338

**Comment by jordan49er** [comment] 2022-09-12 09:18
Hello, this does look good ! However, is it possible to have the star appear next to the data and not have the p-value column ? For example in the marker level "1.07 (0.89)*" ?
If it is not possible it is ok, this is already very good !

**Comment by ddsjoberg** [comment] 2022-09-12 11:13
Thanks for taking a look.

Yes, you can place the stars in any single location. So you can put them next to the first set of data. But not on the subsequent

**Comment by ddsjoberg** [comment] 2022-09-12 13:35
@jordan49er were you envisioning the stars appearing in multiple columns?

**Comment by ddsjoberg** [comment] 2022-09-12 14:09
But there is only one pvalue per variable. Do you have examples of the stars being repeated across all rows in a published article from a journal?

**Comment by jordan49er** [comment] 2022-09-12 14:25
[2015 Boudenot Quick benefits of interval training versus continuous training on[2450].pdf](https://github.com/ddsjoberg/gtsummary/files/9548932/2015.Boudenot.Quick.benefits.of.interval.training.versus.continuous.training.on.2450.pdf)
The tables 3 and 4 illustrate best what the tables could ideally look like, I really hope this helps ! Thank you for all your help!

**Comment by ddsjoberg** [comment] 2022-09-12 14:27
FYI, once the stars are created with `add_significance_stars()`, they can be placed multiple places. But the function will only place them in a single location (which I think is reasonable).

``` r
library(gtsummary)

tbl <-
  trial %>%
  tbl_summary(
    by = grade, 
    include = c(age, marker),
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  add_p(test = everything() ~ "aov") %>%
  add_significance_stars(pattern = "{stat_1}{stars}") %>%
  modify_column_merge(pattern = "{stat_2}{stars}") %>%
  modify_column_merge(pattern = "{stat_3}{stars}") %>%
  modify_column_hide(p.value) 
```
![image](https://user-images.githubusercontent.com/26774684/189679545-013495c1-e67d-4066-9c38-806d9dc6515a.png)

<sup>Created on 2022-09-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


As a warning: I expect the gt package to update their implementation of column merging and i am not sure if a single column can be merged to multiple columns

**Comment by ddsjoberg** [comment] 2022-09-12 14:40
> [2015 Boudenot Quick benefits of interval training versus continuous training on[2450].pdf](https://github.com/ddsjoberg/gtsummary/files/9548932/2015.Boudenot.Quick.benefits.of.interval.training.versus.continuous.training.on.2450.pdf) The tables 3 and 4 illustrate best what the tables could ideally look like, I really hope this helps ! Thank you for all your help!

These tables are more complex that the ones we're creating in tbl_summary(). They are making comparisons across row and also across columns, and adding symbols everywhere to indicate the various comparisons. 

So, yes, you can construct these in gtsummary, but it'll be a manual label of love on the users' part since we don't include the functionality of comparing means across rows.

**Comment by jordan49er** [comment] 2022-09-12 14:44
I understand ! Just being able to add the significance stars on an anova will be very helpful !

**Closed** 2022-09-19 14:30 UTC
Labels: help wanted

**Comment by jordan49er** [comment] 2022-09-27 13:33
Hello, I see that this issue has been closed, but the code doesn't work ? Is there an update to do ? (It's the first time I use github)

Thanks

**Comment by ddsjoberg** [comment] 2022-09-27 13:43
what code doesn't work @jordan49er ?

**Comment by jordan49er** [comment] 2022-09-27 13:45
When I do this : 
tbl <-
  trial %>%
  tbl_summary(
    by = grade, 
    include = c(age, marker),
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  add_p(test = everything() ~ "aov") %>%
  add_significance_stars(pattern = "{stat_1}{stars}") %>%
  modify_column_merge(pattern = "{stat_2}{stars}") %>%
  modify_column_merge(pattern = "{stat_3}{stars}") %>%
  modify_column_hide(p.value) 

I get the error : Error in argument 'x='. Expecting object of class 'tbl_regression', or 'tbl_uvregression'

**Comment by ddsjoberg** [comment] 2022-09-27 13:47
@jordan49er do you have the dev version of the package installed from GitHub?

**Comment by jordan49er** [comment] 2022-09-27 13:48
No I do not!
